### ISSUE TITLE
C_09_JavaFX.java cannot find symbol: class Alert 

### ISSUE THREAD

**Issue by stevenschwenke** [stevenschwenke/Java8Workshop#2]
Project cannot be checked out and build withouf failure, hence shippable also crashes. On a local build using 1.8u45, everything is fine. Regarding to https://groups.google.com/forum/#!topic/javafxports/IEPEqQ-bBrs Maven uses a wrong Java version, maybe 1.8u0. 
Maybe setting a higher 1.8 version in the pom.xml would help, but I don't know the syntax or if this is even the right approach.

**Comment by stevenschwenke** [comment]
Files an issue for the shippable guys: https://github.com/Shippable/support/issues/1649

**Comment by stevenschwenke** [comment]
Current state monitored in [this blog article](http://stevenschwenke.de/cannotFindSymbolInTravisAndShippable). Travis can be configured to use JDK 1.8u45, see the linked article. Shippable seem to have problems with that. Workaround for this repository: Used Travis and Shippable - at least one of them builds fine. 

Because I know the reason why Shippable has trouble building this repository and Travis is working fine, issue closed.
